// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkNi6uC-ozG3P7rjFLIZ2UXlfwzFV_P7M',
    appId: '1:288624476094:web:c8d4793a3125de797443ef',
    messagingSenderId: '288624476094',
    projectId: 'chatbot-app-6b1f6',
    authDomain: 'chatbot-app-6b1f6.firebaseapp.com',
    storageBucket: 'chatbot-app-6b1f6.firebasestorage.app',
    measurementId: 'G-HCPVH6GF9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCua8cRj71xz8cQExrdmGUD9PLXw7YKM9Q',
    appId: '1:288624476094:android:5fe77218e5f2103d7443ef',
    messagingSenderId: '288624476094',
    projectId: 'chatbot-app-6b1f6',
    storageBucket: 'chatbot-app-6b1f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_af_6U2sf7789yNIEF8WaS10L8qBvg0',
    appId: '1:288624476094:ios:2a6806bfefc16b3e7443ef',
    messagingSenderId: '288624476094',
    projectId: 'chatbot-app-6b1f6',
    storageBucket: 'chatbot-app-6b1f6.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatbootApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj_af_6U2sf7789yNIEF8WaS10L8qBvg0',
    appId: '1:288624476094:ios:2a6806bfefc16b3e7443ef',
    messagingSenderId: '288624476094',
    projectId: 'chatbot-app-6b1f6',
    storageBucket: 'chatbot-app-6b1f6.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatbootApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkNi6uC-ozG3P7rjFLIZ2UXlfwzFV_P7M',
    appId: '1:288624476094:web:300807f64ad68d547443ef',
    messagingSenderId: '288624476094',
    projectId: 'chatbot-app-6b1f6',
    authDomain: 'chatbot-app-6b1f6.firebaseapp.com',
    storageBucket: 'chatbot-app-6b1f6.firebasestorage.app',
    measurementId: 'G-Q45QE8YMFR',
  );
}
